# Generated by Django 5.2.4 on 2025-08-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_cartitem_user_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
